# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib/qt/gerbil_gui/mainwindow.ui'
#
# Created: Thu Nov 17 09:41:32 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 672)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("#lcdNumber_mx { color: #ab1111; }\n"
"#lcdNumber_my { color: #ab1111; }\n"
"#lcdNumber_mz { color: #ab1111; }\n"
"#lcdNumber_wx { color: #0e8005; }\n"
"#lcdNumber_wy { color: #0e8005; }\n"
"#lcdNumber_wz { color: #0e8005; }\n"
"#lcdNumber_mx { color: #ab1111; }\n"
"#lcdNumber_my { color: #ab1111; }\n"
"#lcdNumber_mz { color: #ab1111; }")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 0, 1, 1)
        self.horizontalSlider_spindle_factor = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_spindle_factor.setMaximum(100)
        self.horizontalSlider_spindle_factor.setProperty("value", 100)
        self.horizontalSlider_spindle_factor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_spindle_factor.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_spindle_factor.setTickInterval(10)
        self.horizontalSlider_spindle_factor.setObjectName("horizontalSlider_spindle_factor")
        self.gridLayout.addWidget(self.horizontalSlider_spindle_factor, 17, 0, 1, 3)
        self.horizontalSlider_feed_override = QtWidgets.QSlider(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_feed_override.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_feed_override.setSizePolicy(sizePolicy)
        self.horizontalSlider_feed_override.setMinimum(0)
        self.horizontalSlider_feed_override.setMaximum(100)
        self.horizontalSlider_feed_override.setSingleStep(5)
        self.horizontalSlider_feed_override.setPageStep(10)
        self.horizontalSlider_feed_override.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_feed_override.setInvertedAppearance(False)
        self.horizontalSlider_feed_override.setInvertedControls(False)
        self.horizontalSlider_feed_override.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_feed_override.setTickInterval(10)
        self.horizontalSlider_feed_override.setObjectName("horizontalSlider_feed_override")
        self.gridLayout.addWidget(self.horizontalSlider_feed_override, 19, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_feed_override = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_feed_override.setObjectName("checkBox_feed_override")
        self.horizontalLayout_3.addWidget(self.checkBox_feed_override)
        self.lcdNumber_feed_override = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber_feed_override.setMaximumSize(QtCore.QSize(16777, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_feed_override.setFont(font)
        self.lcdNumber_feed_override.setStyleSheet("color: green")
        self.lcdNumber_feed_override.setDigitCount(4)
        self.lcdNumber_feed_override.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_feed_override.setProperty("value", 100.0)
        self.lcdNumber_feed_override.setProperty("intValue", 100)
        self.lcdNumber_feed_override.setObjectName("lcdNumber_feed_override")
        self.horizontalLayout_3.addWidget(self.lcdNumber_feed_override)
        self.lcdNumber_feed_current = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber_feed_current.setStyleSheet("")
        self.lcdNumber_feed_current.setDigitCount(4)
        self.lcdNumber_feed_current.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_feed_current.setObjectName("lcdNumber_feed_current")
        self.horizontalLayout_3.addWidget(self.lcdNumber_feed_current)
        self.gridLayout.addLayout(self.horizontalLayout_3, 18, 0, 1, 3)
        self.label_current_gcode = QtWidgets.QLabel(self.centralWidget)
        self.label_current_gcode.setMinimumSize(QtCore.QSize(200, 0))
        self.label_current_gcode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_gcode.setFont(font)
        self.label_current_gcode.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_current_gcode.setObjectName("label_current_gcode")
        self.gridLayout.addWidget(self.label_current_gcode, 21, 12, 1, 4)
        self.gridLayout_right = QtWidgets.QGridLayout()
        self.gridLayout_right.setObjectName("gridLayout_right")
        self.label_bufsize = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_bufsize.setFont(font)
        self.label_bufsize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bufsize.setObjectName("label_bufsize")
        self.gridLayout_right.addWidget(self.label_bufsize, 1, 0, 1, 1)
        self.checkBox_incremental = QtWidgets.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_incremental.setFont(font)
        self.checkBox_incremental.setObjectName("checkBox_incremental")
        self.gridLayout_right.addWidget(self.checkBox_incremental, 2, 0, 1, 1)
        self.pushButton_job_run = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_job_run.sizePolicy().hasHeightForWidth())
        self.pushButton_job_run.setSizePolicy(sizePolicy)
        self.pushButton_job_run.setObjectName("pushButton_job_run")
        self.gridLayout_right.addWidget(self.pushButton_job_run, 4, 0, 1, 2)
        self.pushButton_job_halt = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_job_halt.setObjectName("pushButton_job_halt")
        self.gridLayout_right.addWidget(self.pushButton_job_halt, 5, 0, 1, 2)
        self.pushButton_job_new = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_job_new.setObjectName("pushButton_job_new")
        self.gridLayout_right.addWidget(self.pushButton_job_new, 3, 0, 1, 2)
        self.comboBox_target = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_target.setMaximumSize(QtCore.QSize(85, 16777215))
        self.comboBox_target.setObjectName("comboBox_target")
        self.gridLayout_right.addWidget(self.comboBox_target, 0, 0, 1, 1)
        self.listWidget_logoutput = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_logoutput.sizePolicy().hasHeightForWidth())
        self.listWidget_logoutput.setSizePolicy(sizePolicy)
        self.listWidget_logoutput.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget_logoutput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(8)
        self.listWidget_logoutput.setFont(font)
        self.listWidget_logoutput.setObjectName("listWidget_logoutput")
        self.gridLayout_right.addWidget(self.listWidget_logoutput, 6, 0, 1, 2)
        self.spinBox_start_line = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_start_line.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBox_start_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_start_line.setMinimum(0)
        self.spinBox_start_line.setMaximum(99999999)
        self.spinBox_start_line.setSingleStep(1)
        self.spinBox_start_line.setProperty("value", 1)
        self.spinBox_start_line.setObjectName("spinBox_start_line")
        self.gridLayout_right.addWidget(self.spinBox_start_line, 0, 1, 1, 1)
        self.label_current_line_number = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_line_number.setFont(font)
        self.label_current_line_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_current_line_number.setObjectName("label_current_line_number")
        self.gridLayout_right.addWidget(self.label_current_line_number, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_right, 0, 14, 21, 2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_script = QtWidgets.QWidget()
        self.tab_script.setObjectName("tab_script")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_script)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plainTextEdit_script = QtWidgets.QPlainTextEdit(self.tab_script)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_script.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_script.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.plainTextEdit_script.setFont(font)
        self.plainTextEdit_script.setObjectName("plainTextEdit_script")
        self.gridLayout_5.addWidget(self.plainTextEdit_script, 0, 0, 1, 3)
        self.pushButton_script_run = QtWidgets.QPushButton(self.tab_script)
        self.pushButton_script_run.setObjectName("pushButton_script_run")
        self.gridLayout_5.addWidget(self.pushButton_script_run, 1, 2, 1, 1)
        self.label_script_filename = QtWidgets.QLabel(self.tab_script)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_script_filename.sizePolicy().hasHeightForWidth())
        self.label_script_filename.setSizePolicy(sizePolicy)
        self.label_script_filename.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_script_filename.setFont(font)
        self.label_script_filename.setObjectName("label_script_filename")
        self.gridLayout_5.addWidget(self.label_script_filename, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_script, "")
        self.tab_preprocessor = QtWidgets.QWidget()
        self.tab_preprocessor.setObjectName("tab_preprocessor")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_preprocessor)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_variables = QtWidgets.QTableWidget(self.tab_preprocessor)
        self.tableWidget_variables.setRowCount(10)
        self.tableWidget_variables.setColumnCount(2)
        self.tableWidget_variables.setObjectName("tableWidget_variables")
        self.tableWidget_variables.horizontalHeader().setVisible(False)
        self.tableWidget_variables.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tableWidget_variables, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_preprocessor, "")
        self.tab_jog = QtWidgets.QWidget()
        self.tab_jog.setObjectName("tab_jog")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_jog)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_jog_container = QtWidgets.QGridLayout()
        self.gridLayout_jog_container.setObjectName("gridLayout_jog_container")
        self.gridLayout_10.addLayout(self.gridLayout_jog_container, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_jog, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plainTextEdit_job = QtWidgets.QPlainTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(8)
        self.plainTextEdit_job.setFont(font)
        self.plainTextEdit_job.setObjectName("plainTextEdit_job")
        self.gridLayout_8.addWidget(self.plainTextEdit_job, 1, 0, 1, 1)
        self.pushButton_show_buffer = QtWidgets.QPushButton(self.tab)
        self.pushButton_show_buffer.setObjectName("pushButton_show_buffer")
        self.gridLayout_8.addWidget(self.pushButton_show_buffer, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_settings_download_grbl = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_settings_download_grbl.setObjectName("pushButton_settings_download_grbl")
        self.gridLayout_13.addWidget(self.pushButton_settings_download_grbl, 0, 0, 1, 1)
        self.pushButton_settings_load_file = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_settings_load_file.setObjectName("pushButton_settings_load_file")
        self.gridLayout_13.addWidget(self.pushButton_settings_load_file, 0, 1, 1, 1)
        self.pushButton_settings_upload_grbl = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_settings_upload_grbl.setObjectName("pushButton_settings_upload_grbl")
        self.gridLayout_13.addWidget(self.pushButton_settings_upload_grbl, 2, 0, 1, 1)
        self.pushButton_settings_save_file = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_settings_save_file.setObjectName("pushButton_settings_save_file")
        self.gridLayout_13.addWidget(self.pushButton_settings_save_file, 2, 1, 1, 1)
        self.tableWidget_settings = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_settings.setFont(font)
        self.tableWidget_settings.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_settings.setRowCount(32)
        self.tableWidget_settings.setColumnCount(3)
        self.tableWidget_settings.setObjectName("tableWidget_settings")
        self.tableWidget_settings.horizontalHeader().setVisible(False)
        self.tableWidget_settings.horizontalHeader().setMinimumSectionSize(19)
        self.tableWidget_settings.verticalHeader().setVisible(False)
        self.gridLayout_13.addWidget(self.tableWidget_settings, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_11.addWidget(self.tabWidget, 1, 0, 2, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 0, 10, 22, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar_buffer = QtWidgets.QProgressBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_buffer.sizePolicy().hasHeightForWidth())
        self.progressBar_buffer.setSizePolicy(sizePolicy)
        self.progressBar_buffer.setMaximumSize(QtCore.QSize(300, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.progressBar_buffer.setFont(font)
        self.progressBar_buffer.setProperty("value", 0)
        self.progressBar_buffer.setObjectName("progressBar_buffer")
        self.verticalLayout_2.addWidget(self.progressBar_buffer)
        self.progressBar_job = QtWidgets.QProgressBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_job.sizePolicy().hasHeightForWidth())
        self.progressBar_job.setSizePolicy(sizePolicy)
        self.progressBar_job.setMaximumSize(QtCore.QSize(300, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.progressBar_job.setFont(font)
        self.progressBar_job.setProperty("value", 0)
        self.progressBar_job.setObjectName("progressBar_job")
        self.verticalLayout_2.addWidget(self.progressBar_job)
        self.gridLayout.addLayout(self.verticalLayout_2, 21, 0, 1, 3)
        self.verticalLayout_xyz = QtWidgets.QVBoxLayout()
        self.verticalLayout_xyz.setSpacing(0)
        self.verticalLayout_xyz.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_xyz.setObjectName("verticalLayout_xyz")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_xyz.addWidget(self.label_9)
        self.lcdNumber_mx = QtWidgets.QLCDNumber(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_mx.sizePolicy().hasHeightForWidth())
        self.lcdNumber_mx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_mx.setFont(font)
        self.lcdNumber_mx.setDigitCount(8)
        self.lcdNumber_mx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_mx.setProperty("value", 8888.888)
        self.lcdNumber_mx.setObjectName("lcdNumber_mx")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_mx)
        self.lcdNumber_my = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_my.setFont(font)
        self.lcdNumber_my.setDigitCount(8)
        self.lcdNumber_my.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_my.setProperty("value", 8888.888)
        self.lcdNumber_my.setObjectName("lcdNumber_my")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_my)
        self.lcdNumber_mz = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_mz.setFont(font)
        self.lcdNumber_mz.setSmallDecimalPoint(False)
        self.lcdNumber_mz.setDigitCount(8)
        self.lcdNumber_mz.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_mz.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_mz.setProperty("value", 8888.888)
        self.lcdNumber_mz.setObjectName("lcdNumber_mz")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_mz)
        self.comboBox_coordinate_systems = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_coordinate_systems.setObjectName("comboBox_coordinate_systems")
        self.verticalLayout_xyz.addWidget(self.comboBox_coordinate_systems)
        self.pushButton_current_cs_setzero = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_current_cs_setzero.setObjectName("pushButton_current_cs_setzero")
        self.verticalLayout_xyz.addWidget(self.pushButton_current_cs_setzero)
        self.lcdNumber_wx = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_wx.setFont(font)
        self.lcdNumber_wx.setDigitCount(8)
        self.lcdNumber_wx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_wx.setProperty("value", 8888.888)
        self.lcdNumber_wx.setObjectName("lcdNumber_wx")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_wx)
        self.lcdNumber_wy = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lcdNumber_wy.setFont(font)
        self.lcdNumber_wy.setDigitCount(8)
        self.lcdNumber_wy.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_wy.setProperty("value", 8888.888)
        self.lcdNumber_wy.setObjectName("lcdNumber_wy")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_wy)
        self.lcdNumber_wz = QtWidgets.QLCDNumber(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_wz.setFont(font)
        self.lcdNumber_wz.setDigitCount(8)
        self.lcdNumber_wz.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_wz.setProperty("value", 8888.888)
        self.lcdNumber_wz.setObjectName("lcdNumber_wz")
        self.verticalLayout_xyz.addWidget(self.lcdNumber_wz)
        self.gridLayout.addLayout(self.verticalLayout_xyz, 0, 0, 13, 1)
        self.scrollArea_loginput = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_loginput.sizePolicy().hasHeightForWidth())
        self.scrollArea_loginput.setSizePolicy(sizePolicy)
        self.scrollArea_loginput.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea_loginput.setMaximumSize(QtCore.QSize(16777, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(9)
        self.scrollArea_loginput.setFont(font)
        self.scrollArea_loginput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_loginput.setWidgetResizable(True)
        self.scrollArea_loginput.setObjectName("scrollArea_loginput")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 285, 571))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(9)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_loginput.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea_loginput, 0, 12, 21, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_zplus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_zplus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_zplus.setFont(font)
        self.pushButton_zplus.setObjectName("pushButton_zplus")
        self.gridLayout_3.addWidget(self.pushButton_zplus, 3, 1, 1, 1)
        self.pushButton_xplus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_xplus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_xplus.setFont(font)
        self.pushButton_xplus.setObjectName("pushButton_xplus")
        self.gridLayout_3.addWidget(self.pushButton_xplus, 1, 1, 1, 1)
        self.pushButton_zminus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_zminus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_zminus.setFont(font)
        self.pushButton_zminus.setObjectName("pushButton_zminus")
        self.gridLayout_3.addWidget(self.pushButton_zminus, 3, 0, 1, 1)
        self.pushButton_yplus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_yplus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_yplus.setFont(font)
        self.pushButton_yplus.setObjectName("pushButton_yplus")
        self.gridLayout_3.addWidget(self.pushButton_yplus, 2, 0, 1, 1)
        self.pushButton_xminus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_xminus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_xminus.setFont(font)
        self.pushButton_xminus.setObjectName("pushButton_xminus")
        self.gridLayout_3.addWidget(self.pushButton_xminus, 1, 0, 1, 1)
        self.doubleSpinBox_jogstep = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_jogstep.setDecimals(1)
        self.doubleSpinBox_jogstep.setMinimum(0.1)
        self.doubleSpinBox_jogstep.setMaximum(100.0)
        self.doubleSpinBox_jogstep.setSingleStep(0.1)
        self.doubleSpinBox_jogstep.setProperty("value", 1.0)
        self.doubleSpinBox_jogstep.setObjectName("doubleSpinBox_jogstep")
        self.gridLayout_3.addWidget(self.doubleSpinBox_jogstep, 0, 0, 1, 2)
        self.pushButton_yminus = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_yminus.sizePolicy().hasHeightForWidth())
        self.pushButton_yminus.setSizePolicy(sizePolicy)
        self.pushButton_yminus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_yminus.setFont(font)
        self.pushButton_yminus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_yminus.setDefault(False)
        self.pushButton_yminus.setFlat(False)
        self.pushButton_yminus.setObjectName("pushButton_yminus")
        self.gridLayout_3.addWidget(self.pushButton_yminus, 2, 1, 1, 1)
        self.pushButton_g53z0 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_g53z0.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_g53z0.setFont(font)
        self.pushButton_g53z0.setObjectName("pushButton_g53z0")
        self.gridLayout_3.addWidget(self.pushButton_g53z0, 4, 0, 1, 1)
        self.pushButton_g53min = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_g53min.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_g53min.setFont(font)
        self.pushButton_g53min.setObjectName("pushButton_g53min")
        self.gridLayout_3.addWidget(self.pushButton_g53min, 5, 0, 1, 1)
        self.pushButton_g53x0y0 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_g53x0y0.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_g53x0y0.setFont(font)
        self.pushButton_g53x0y0.setObjectName("pushButton_g53x0y0")
        self.gridLayout_3.addWidget(self.pushButton_g53x0y0, 4, 1, 1, 1)
        self.pushButton_g0x0y0 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_g0x0y0.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_g0x0y0.setFont(font)
        self.pushButton_g0x0y0.setObjectName("pushButton_g0x0y0")
        self.gridLayout_3.addWidget(self.pushButton_g0x0y0, 5, 1, 1, 1)
        self.pushButton_spindleoff = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_spindleoff.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_spindleoff.setFont(font)
        self.pushButton_spindleoff.setObjectName("pushButton_spindleoff")
        self.gridLayout_3.addWidget(self.pushButton_spindleoff, 7, 0, 1, 1)
        self.pushButton_spindleon = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_spindleon.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_spindleon.setFont(font)
        self.pushButton_spindleon.setObjectName("pushButton_spindleon")
        self.gridLayout_3.addWidget(self.pushButton_spindleon, 7, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 13, 0, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_state = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state.sizePolicy().hasHeightForWidth())
        self.label_state.setSizePolicy(sizePolicy)
        self.label_state.setMinimumSize(QtCore.QSize(0, 0))
        self.label_state.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_state.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_state.setFont(font)
        self.label_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state.setObjectName("label_state")
        self.verticalLayout.addWidget(self.label_state)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 2, 2)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_12.setVerticalSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_spindle_state = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spindle_state.sizePolicy().hasHeightForWidth())
        self.label_spindle_state.setSizePolicy(sizePolicy)
        self.label_spindle_state.setObjectName("label_spindle_state")
        self.gridLayout_12.addWidget(self.label_spindle_state, 6, 1, 1, 1)
        self.label_motionmode = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_motionmode.sizePolicy().hasHeightForWidth())
        self.label_motionmode.setSizePolicy(sizePolicy)
        self.label_motionmode.setObjectName("label_motionmode")
        self.gridLayout_12.addWidget(self.label_motionmode, 0, 1, 1, 1)
        self.label_planemode = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_planemode.sizePolicy().hasHeightForWidth())
        self.label_planemode.setSizePolicy(sizePolicy)
        self.label_planemode.setObjectName("label_planemode")
        self.gridLayout_12.addWidget(self.label_planemode, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_12.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_distmode = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_distmode.sizePolicy().hasHeightForWidth())
        self.label_distmode.setSizePolicy(sizePolicy)
        self.label_distmode.setObjectName("label_distmode")
        self.gridLayout_12.addWidget(self.label_distmode, 2, 1, 1, 1)
        self.label_programmode = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_programmode.sizePolicy().hasHeightForWidth())
        self.label_programmode.setSizePolicy(sizePolicy)
        self.label_programmode.setObjectName("label_programmode")
        self.gridLayout_12.addWidget(self.label_programmode, 5, 1, 1, 1)
        self.label_unitmode = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_unitmode.sizePolicy().hasHeightForWidth())
        self.label_unitmode.setSizePolicy(sizePolicy)
        self.label_unitmode.setObjectName("label_unitmode")
        self.gridLayout_12.addWidget(self.label_unitmode, 4, 1, 1, 1)
        self.label_feedmode = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_feedmode.sizePolicy().hasHeightForWidth())
        self.label_feedmode.setSizePolicy(sizePolicy)
        self.label_feedmode.setObjectName("label_feedmode")
        self.gridLayout_12.addWidget(self.label_feedmode, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_12.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_current_rpm = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_current_rpm.sizePolicy().hasHeightForWidth())
        self.label_current_rpm.setSizePolicy(sizePolicy)
        self.label_current_rpm.setObjectName("label_current_rpm")
        self.gridLayout_12.addWidget(self.label_current_rpm, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_12.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_jobtime = QtWidgets.QLabel(self.centralWidget)
        self.label_jobtime.setObjectName("label_jobtime")
        self.gridLayout_12.addWidget(self.label_jobtime, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 9, 0, 1, 1)
        self.label_runningtime = QtWidgets.QLabel(self.centralWidget)
        self.label_runningtime.setObjectName("label_runningtime")
        self.gridLayout_12.addWidget(self.label_runningtime, 9, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_eta = QtWidgets.QLabel(self.centralWidget)
        self.label_eta.setObjectName("label_eta")
        self.gridLayout_12.addWidget(self.label_eta, 10, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_12, 2, 1, 11, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_abort = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_abort.setFont(font)
        self.pushButton_abort.setAutoFillBackground(False)
        self.pushButton_abort.setStyleSheet("")
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.gridLayout_2.addWidget(self.pushButton_abort, 0, 0, 1, 1)
        self.pushButton_resume = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_resume.setStyleSheet("color: green")
        self.pushButton_resume.setObjectName("pushButton_resume")
        self.gridLayout_2.addWidget(self.pushButton_resume, 2, 1, 1, 1)
        self.pushButton_killalarm = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_killalarm.setStyleSheet("color: red")
        self.pushButton_killalarm.setObjectName("pushButton_killalarm")
        self.gridLayout_2.addWidget(self.pushButton_killalarm, 0, 1, 1, 1)
        self.pushButton_homing = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_homing.setStyleSheet("color: blue")
        self.pushButton_homing.setObjectName("pushButton_homing")
        self.gridLayout_2.addWidget(self.pushButton_homing, 1, 0, 1, 1)
        self.pushButton_check = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_check.setStyleSheet("color: orange;")
        self.pushButton_check.setObjectName("pushButton_check")
        self.gridLayout_2.addWidget(self.pushButton_check, 1, 1, 1, 1)
        self.pushButton_hold = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_hold.setStyleSheet("color: yellow;")
        self.pushButton_hold.setObjectName("pushButton_hold")
        self.gridLayout_2.addWidget(self.pushButton_hold, 2, 0, 1, 1)
        self.pushButton_bbox = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_bbox.setObjectName("pushButton_bbox")
        self.gridLayout_2.addWidget(self.pushButton_bbox, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 13, 1, 1, 2)
        self.label_grbl = QtWidgets.QLabel(self.centralWidget)
        self.label_grbl.setGeometry(QtCore.QRect(279, 493, 334, 31))
        self.label_grbl.setText("")
        self.label_grbl.setObjectName("label_grbl")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setMinimumSize(QtCore.QSize(0, 31))
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 16))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_feed_override.setText(_translate("MainWindow", "Feed override"))
        self.label_current_gcode.setText(_translate("MainWindow", "; current_gcode_line"))
        self.label_bufsize.setText(_translate("MainWindow", "0"))
        self.checkBox_incremental.setText(_translate("MainWindow", "Stream Increm."))
        self.pushButton_job_run.setText(_translate("MainWindow", "Run"))
        self.pushButton_job_halt.setText(_translate("MainWindow", "Stop Stream"))
        self.pushButton_job_new.setText(_translate("MainWindow", "New"))
        self.label_current_line_number.setText(_translate("MainWindow", "0"))
        self.plainTextEdit_script.setPlainText(_translate("MainWindow", "# my script"))
        self.pushButton_script_run.setText(_translate("MainWindow", "Execute"))
        self.label_script_filename.setText(_translate("MainWindow", "New file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_script), _translate("MainWindow", "Scripting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preprocessor), _translate("MainWindow", "Preprocessor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_jog), _translate("MainWindow", "Jogging"))
        self.pushButton_show_buffer.setText(_translate("MainWindow", "Show Buffer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Buffer"))
        self.pushButton_settings_download_grbl.setText(_translate("MainWindow", "Download from Grbl"))
        self.pushButton_settings_load_file.setText(_translate("MainWindow", "Load from File"))
        self.pushButton_settings_upload_grbl.setText(_translate("MainWindow", "Upload into Grbl"))
        self.pushButton_settings_save_file.setText(_translate("MainWindow", "Save into File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.label_9.setText(_translate("MainWindow", "G53"))
        self.pushButton_current_cs_setzero.setText(_translate("MainWindow", "Set Zero"))
        self.pushButton_zplus.setText(_translate("MainWindow", "Z↑"))
        self.pushButton_xplus.setText(_translate("MainWindow", "X→"))
        self.pushButton_zminus.setText(_translate("MainWindow", "Z↓"))
        self.pushButton_yplus.setText(_translate("MainWindow", "Y↗"))
        self.pushButton_xminus.setText(_translate("MainWindow", "←X"))
        self.pushButton_yminus.setText(_translate("MainWindow", "Y↙"))
        self.pushButton_g53z0.setText(_translate("MainWindow", "Z max"))
        self.pushButton_g53min.setText(_translate("MainWindow", "LLC"))
        self.pushButton_g53x0y0.setText(_translate("MainWindow", "URC"))
        self.pushButton_g0x0y0.setText(_translate("MainWindow", "Origin"))
        self.pushButton_spindleoff.setText(_translate("MainWindow", "Sp. off"))
        self.pushButton_spindleon.setText(_translate("MainWindow", "Sp. max"))
        self.label_state.setText(_translate("MainWindow", "disconnected"))
        self.label_spindle_state.setText(_translate("MainWindow", "M5"))
        self.label_motionmode.setText(_translate("MainWindow", "G0"))
        self.label_planemode.setText(_translate("MainWindow", "G17"))
        self.label.setText(_translate("MainWindow", "Motion"))
        self.label_4.setText(_translate("MainWindow", "Unit"))
        self.label_distmode.setText(_translate("MainWindow", "G90"))
        self.label_programmode.setText(_translate("MainWindow", "M0"))
        self.label_unitmode.setText(_translate("MainWindow", "G21"))
        self.label_feedmode.setText(_translate("MainWindow", "G94"))
        self.label_10.setText(_translate("MainWindow", "Distance"))
        self.label_12.setText(_translate("MainWindow", "RPM"))
        self.label_current_rpm.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Plane"))
        self.label_6.setText(_translate("MainWindow", "Spindle"))
        self.label_jobtime.setText(_translate("MainWindow", "00:00:00"))
        self.label_3.setText(_translate("MainWindow", "Feed"))
        self.label_7.setText(_translate("MainWindow", "Job Time"))
        self.label_5.setText(_translate("MainWindow", "Program"))
        self.label_8.setText(_translate("MainWindow", "Running"))
        self.label_runningtime.setText(_translate("MainWindow", "00:00:00"))
        self.label_11.setText(_translate("MainWindow", "ETA"))
        self.label_eta.setText(_translate("MainWindow", "00:00:00"))
        self.pushButton_abort.setText(_translate("MainWindow", "RESET"))
        self.pushButton_resume.setText(_translate("MainWindow", "Resume ~"))
        self.pushButton_killalarm.setText(_translate("MainWindow", "Kill Alarm"))
        self.pushButton_homing.setText(_translate("MainWindow", "Homing"))
        self.pushButton_check.setText(_translate("MainWindow", "Check"))
        self.pushButton_hold.setText(_translate("MainWindow", "Hold !"))
        self.pushButton_bbox.setText(_translate("MainWindow", "BBOX"))

